/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package console;

import org.junit.Test;
import static org.junit.Assert.*;

public class ConsoleTest {
    // TODO: add some tests here
}
